### ISSUE TITLE
Wrong Authorization Message Displaying After Credentials

### ISSUE THREAD

**Issue by DeeKoy** [kbeflo/evilportals#8]
On all of these portals I've noticed that after entering in credentials, I get the showError() authorization response as opposed to the showSuccess() response. I am still investigating - but from what I've seen the Portal.php code seems sound. Is the problem with these portals specifically, or should I continue to investigate the EvilPortal code? Is anyone else having this issue?

**Comment by kbeflo** [comment]
Regarding the issue on Evil Portal authorization, I have just ignored this for a while because after error authorization, the portal still posts the credentials to the Pineapple and closes the captive portal after. 

I haven't looked at this for a while but the problem may be the Portal.php code on the portals, or on the Evil Portal module. I suggest using the latest nightly build of Evil Portal.

**Comment by DeeKoy** [comment]
Thanks for the reply. I might just disable this part of the code entirely. The problem I found is that iPhones actually hang on the authorization page as opposed to closing and redirecting past it. I think the problem is with EvilPortal - not with your portals specifically. Great job on these. I do have one suggestion/issue that I will post in a new issue.
